name: build-image
run-name: Build shimboot image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            binwalk \
            pcre2-utils \
            pv \
            cgpt

      - name: Make scripts executable
        run: |
          find . -type f -name "*.sh" -exec chmod +x {} \;

      - name: Run build
        run: sudo bash ./build_complete.sh dedede distro=gentoo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shimboot_dedede
          path: data/
